### ISSUE TITLE
Set simulation time

### ISSUE THREAD

**Issue by cvalcort** [PenRed/PenRed#42]
Sorry if this is already built-in. I'm a new user, and I couldn't find in the documentation anything related. It would be helpful to stop the simulation at a user-defined simulation time. Some servers have a maximum computation time, and processes can be interrupted, leaving corrupted tallies. Specifying a maximum simulation time avoids this by finishing the tally generation before the server stops the process.

**Comment by vigial** [comment]
This feature is now implemented in the branch *v-1.8.1*. We have tested it, but additional tests are always welcome :)

To set the maximum simulation time, specify the corresponding parameter in the configuration file, as follows:

simulation/max-time 500

where *500* is the maximum simulation time in seconds. We plan to include the #43 feature in this version, so it will be pulled once completed.
