### ISSUE TITLE
Generation particle filter for tallies

### ISSUE THREAD

**Issue by cvalcort** [PenRed/PenRed#43]
Some research requires discriminating between primary photons, those scattered one time and those scattered several times (the so-called PSS data). Reading the PENELOPE documentation, the MC system leaves the same ILB(1) for scattered photons to avoid further manipulation. The user can use ILB(5) for that purpose, but this requires little modifications in several files, always in a painful iteration (if there is a variance reduction, it worsens). It would be great to have this feature already included in PenRed.

**Comment by vigial** [comment]
Thanks for the references and description. I agree that having this information accessible in a tally can be useful. Probably, the best way to implement it is to have a specific tally callback to be called when some particle is stored in a stack. Then, with the *tally_beginPart* tally callback, and taking into account that the stacks uses a FILO queue, we can know when a particle is read from the stack and retrieve the corresponding bkp value. 

This approach does not affect the rest of the code, which is always appreciated. Let me study this feature to implement it in a new version.

**Comment by vigial** [comment]
This functionallity has been added in version 1.8.1 #44 . Now, tallies can get information from particle stacks, what has been used to implement the PSS tally. This one uses different tally instances to register primary, scatter and multi-scatter radiation effect depending on the selected scoring tally and other parameters. All information can be found in the documentation. 

Please, if you test it, report any bug or unexpected behaviour.
