### ISSUE TITLE
PenRed User Manual (July 11, 2024) needs an update

### ISSUE THREAD

**Issue by cvalcort** [PenRed/PenRed#64]
I've been working with IForcing, and codes 65, 66, and 67  in the user manual recommend the form, e.g., VR/IForcing/bodies/VR1/factor. However, this command doesn't work. Instead, the example Quadrics/4-x-ray-tube/ uses VR/IForcing/VR1/factor, which actually works.

Regards!

**Comment by vigial** [comment]
You’re correct, the VR documentation is outdated and the correct paths are the ones used in the examples. We’ll update the VR section accordingly and release a revised manual soon.

Thank you for reporting this issue!

Regards

**Comment by sanogil** [comment]
The documentation has been corrected in version v.1.12 and is now consistent with the examples of quadrics folder. 
The merge to master is still pending. 

Thank you for the report.

Regards

**Comment by sanogil** [comment]
The documentation has been corrected in version v.1.12 and is now consistent with the examples of quadrics folder. 
The merge to master is still pending. 

Thank you for the report.

**Comment by vigial** [comment]
The corrections have been merged to master, thanks for reporting!
